db/index.js

tested a push using agile/github workflow

#1 test push

---

index.js

Added console.log

---

db/index.js
package-lock.json

test heroku error

---

db/seedData.js

Add: Corrected DB

---

db/client.js

updated dbname

---

db/client.js
schema.sql

finished creating initial users

---

api/auth.js

created .env file

---

api/users.js
db/models/users.js

added functions to both the user db and api

user-db-api: added functions to both

---

db/models/cart_items.js
db/models/discount.js
db/models/order_details.js
db/models/order_items.js
db/models/payment_details.js
db/models/product.js
db/models/product_inventory.js
db/models/user_address.js
db/models/user_payment.js
db/models/users.js
db/seedData.js

I fixed camel casing and the dbs will return but some things return null.

fixed camel casing and error in db

---

api/users.js
db/client.js

added functions to user db and api

user-db-api: added funcitons

---

api/product.js
api/users.js
db/models/product.js
db/models/users.js

Still working on patch, we are getting a syntax error on patch.

added to product api

---

api/discount.js

update and delete in discount api and db. Still need to run curl commands

update and delete on discount

---

db/models/discount.js

add update and delete functionality for api/discounts.js

add: update and delete API CRUD

---

api/discount.js
api/index.js
api/payment.js
api/product.js
db/models/discount.js
db/models/order_items.js
db/models/payment_details.js
db/models/product.js
db/seedData.js

added full CRUD to our api and db on payment_details

add: added COMPLETE CRUD for payment_details.js

---

api/order.js
db/models/order_details.js
db/models/order_items.js

added complete crud for db/api of order_details/order_items

add: added COMPLETE CRUD for order.js

---

api/payment.js

fix: type error

---

api/cart.js
api/index.js
db/models/cart_items.js
db/seedData.js

added the create read and get by id to api/db cart_items

add: added to cart_item CRUD

---

api/cart.js

fixed cart issues

---

api/payment.js

added delete router to payment api

add: added delete router to /api/payments.js

---

db/models/index.js
db/models/shop_session.js
db/seedData.js

added ShopSession to our models

fixed models index.js and createShopSession

---

api/index.js
api/shop.js
db/models/shop_session.js

added functionality to see our shop session in the api

add: added functionality to get shopsessions in the api

---

api/index.js
api/shop.js

post route for shop sesh

---

api/shop.js
db/models/shop_session.js

added delete funcs to shopsesh db and api

delete-shopSesh: added db and api delete shopSesh functions

---

api/shop.js

fixed some things for the shopSession delete router

fixed: shop_session api deleterouter

---

db/models/discount.js

added get discount by id

---

api/discount.js
db/models/shop_session.js

fixed discountById api

---

api/discount.js
api/shop.js

update and patch functions for shop

added update and patch for shop

---

api/users.js
db/models/user_address.js
db/models/user_payment.js

added FULL CRUD to the (api/db) user_payment and user_address

add: added full crud for user_payment and user_address

---

api/product.js

fixed the products.js file after mergre conflict

fixed the products.js file after mergre conflict

---

api/cart.js
api/discount.js
api/order.js
api/product.js
api/shop.js
api/users.js
db/models/cart_items.js
db/models/discount.js
db/models/order_items.js
db/models/payment_details.js
db/models/product.js
db/models/product_inventory.js
db/models/shop_session.js
db/models/users.js
db/seedData.js

added post and update for all api files except for users!

fixed patch and post on all files except for users

---

api/auth.js
api/cart.js
api/discount.js
api/order.js
api/payment.js
api/product.js
api/shop.js
api/users.js
db/models/cart_items.js
db/models/discount.js
db/models/order_details.js
db/models/order_items.js
db/models/payment_details.js
db/models/product.js
db/models/product_inventory.js
db/models/shop_session.js
db/models/users.js
db/seedData.js

fixed patch routes to where they return but getting null right now

fixed patch routes

---

api/product.js
api/test-specs/paymentRouter.test.js
api/test-specs/productRouter.test.js
db/models/users.js
db/seedData.js

fixes Apis and made a few tests

fixed apis and made some tests

---

api/users.js
db/models/user_address.js
db/models/user_payment.js

fixed api and db for user payment and db

fixed api and db for user payment and db

---

api/cart.js
api/order.js
api/users.js

added post routes for our userAddress and UserPayment API

add: added post routes for userAddress and UserPayment

---

api/product.js
db/models/product_category.js
db/models/product_inventory.js

added update and delete functions to product inv and product category db.
Also added delete and patch routes to those files api routes

add: added delete and update functions to our productCat and productInv

---

api/product.js
api/shop.js
api/test-specs/cartRouter.test.js
api/test-specs/discount.test.js
api/test-specs/orderRouter.test.js
api/test-specs/paymentRouter.test.js
api/test-specs/shopRouter.test.js
api/test-specs/usersRouter.test.js
api/users.js
db/models/product_inventory.js
db/models/shop_session.js
db/models/users.js
db/seedData.js

added the rest of the tests and beefed up the product inventory

added the rest of the tests and beefed up the product inventory

---

src/imageUrls.js

add: image urls strategy

---

src/components/Footer.js
src/components/styles/Footer.css

chris brown is trash. done with footer!

footer: done with footer

---

src/components/App.js
src/components/CatColumn.js
src/components/index.js
src/components/styles/CatColumn.css

Started the basics of the category column.

started categories

---

src/components/Footer.js
src/components/styles/Footer.css

Re-positioned footer elements and added styling and hover effects.

touched up footer

---

src/components/MyAccount.js
src/components/styles/MyAccount.css

my-account-done: finished my account page

---

src/components/Banner.js
src/components/Header.js
src/components/styles/Banner.css
src/components/styles/Header.css
src/components/styles/Home.css
src/components/styles/Nav.css
src/components/styles/ProductView.css

fixed header component

---

src/components/Checkout.js
src/components/styles/Checkout.css

Jesus Saves!

---

src/components/Cart.js
src/components/Header.js
src/components/MyAccount.js
src/components/Nav.js
src/components/ProductRows.js
src/components/Signup.js
src/components/styles/Cart.css
src/components/styles/MyAccount.css
src/components/styles/ProductRows.css

added account css styling and home button in the header.

added account css styling

---

src/components/App.js
src/components/Login.js
src/components/MyOrders.js
src/components/Signup.js
src/components/index.js
src/components/styles/Cart.css
src/components/styles/Login.css
src/components/styles/MyOrders.css
src/components/styles/Signup.css

added our hardcoded version of my orders!

added our hardcoded version of my orders!

---

src/components/styles/Cart.css

fixed a syntax error in cart.css

fix: syntax error

---

src/components/Cart.js
src/components/styles/Cart.css
src/components/styles/MyAccount.css

fixed some styling issues for the rewards section of our order summary

fix: fixed some styling issues

---

src/components/Login.js
src/components/Nav.js
src/components/Signup.js
src/components/styles/Login.css
src/components/styles/MyAccount.css
src/components/styles/Nav.css
src/components/styles/Signup.css

added styling changes to the sign up and login page

added styling changes to the sign up and login page

---

src/components/styles/Cart.css
src/components/styles/Footer.css
src/components/styles/Home.css
src/components/styles/ProductRows.css
src/components/styles/ProductView.css
src/components/styles/index.css

added some mobile responsiveness to various pages

add: some mobile responsiveness

---

src/components/Login.js
src/components/Signup.js
src/components/styles/Login.css
src/components/styles/Signup.css

added some style changes to login and sign up form

add: added some style changes to login and sign up form

---

src/components/Login.js

fixed login page layout

---

src/components/Cart.js
src/components/Header.js
src/components/Home.js
src/components/Nav.js
src/components/styles/Footer.css
src/components/styles/Header.css
src/components/styles/Home.css
src/components/styles/Nav.css

started adding media queries to home, header, and footer.

started adding media queries to home, header, and footer.

---

src/components/styles/Cart.css

add: styling change to order summary

---

src/components/Footer.js
src/components/styles/Footer.css

Finished styling and repositioning footer links and icons

finished footer links

---

src/components/ProductRows.js
src/components/ProductView.js
src/components/styles/Home.css
src/components/styles/Nav.css
src/components/styles/ProductRows.css
src/components/styles/ProductView.css

finished media queries for nav, header, product rows, product view

finished media queries for nav, header, product rows, product view

---

api/users.js
db/seedData.js
src/axios-services/index.js
src/components/App.js
src/components/Signup.js
src/custom-hooks/useSignUp.js

added sign up functionality/logic to our sign up page

add: added sign up functionality/logic

---

db/seedData.js
src/components/Header.js
src/components/styles/Header.css
src/context/AuthContext.js
src/custom-hooks/logout.js

set up logout function but need to push to home

set up logout function but need to push to home

---

api/product.js
src/axios-services/cart.js
src/axios-services/discount.js
src/axios-services/order.js
src/axios-services/payment.js
src/axios-services/product.js
src/axios-services/shop.js
src/axios-services/users.js
src/components/App.js
src/components/ProductRows.js
src/components/ProductView.js
src/custom-hooks/useMe.js
src/custom-hooks/useProducts.js
src/custom-hooks/useSignUp.js
src/custom-hooks/useSingleProduct.js

Product fetch

---

db/models/users.js
db/seedData.js
package-lock.json
package.json
src/axios-services/product.js
src/axios-services/users.js
src/components/Home.js
src/components/Nav.js
src/components/ProductRows.js
src/components/ProductView.js
src/components/styles/Home.css
src/components/styles/ProductRows.css
src/components/styles/ProductView.css
src/custom-hooks/useLogin.js
src/custom-hooks/useSingleProduct.js

fetched all of the data for product rows

fetched all of the data for product rows

---

api/product.js
db/models/product.js
db/seedData.js
src/components/ProductRows.js
src/components/styles/ProductRows.css

fixed css problems for fetching all product data into rows

fixed css problems for fetching all product data into rows

---

api/product.js
db/seedData.js
src/axios-services/product.js
src/components/App.js
src/components/MyOrders.js
src/components/ProductRows.js
src/components/ProductView.js
src/components/index.js
src/components/styles/ProductRows.css
src/components/styles/ProductView.css
src/custom-hooks/useProducts.js
src/custom-hooks/useSingleProduct.js

fetched data from the backend to product view

fetched data from the backend to product view
